name: deploy-manifests
on:
  push:
    branches:
      - main
    paths:
      - 'Infra/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
            - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save ticketing
      - run: kubectl apply -f Infra/k8 && kubctl apply -f infra/k8s/prod
